### ISSUE TITLE
can't access checkpoint FoodSeg103-SETR-MLA

### ISSUE THREAD

**Issue by biy001** [jamesjg/FoodSAM#1]
Looks like permission is needed to access.

**Comment by jamesjg** [comment]
Hi, I just tried the link again from the installation.md file and was still able to download the checkpoints successfully. The link seems to be working on my end. Could you please try switching networks or using a different browser or device and see if the link is accessible? There might be something with your specific setup that is blocking access.

**Comment by biy001** [comment]
I ended up successfully downloading it from the FoodSeg103 repo. Maybe my setup messed up. Thanks.
https://github.com/LARC-CMU-SMU/FoodSeg103-Benchmark-v1
