### ISSUE TITLE
FoodSeg103-SETR-MLA error

### ISSUE THREAD

**Issue by deeplearnerlcb** [jamesjg/FoodSAM#3]
We're sorry, but **** can't be found in the smu-my.sharepoint.com directory. Please try again later, while we try to automatically fix this for you.

**Comment by starhiking** [comment]
Hi, the foodseg103's official link may have some issues.
We offer an auxiliary link in [BaiduOS Disk](https://pan.baidu.com/s/1o1w_Vejrtd7rvWVorSQZfg?pwd=pyyk).

**Comment by seungwoo-ji-03** [comment]
@deeplearnerlcb 
I think the link below will be helpful.

https://github.com/LARC-CMU-SMU/FoodSeg103-Benchmark-v1/issues/22

**Comment by starhiking** [comment]
I also upload it  on the [google drive](https://drive.google.com/drive/folders/1T3zgJzWvgDZKF8bu-8HcNIRzIoJ6uU6A?usp=sharing)
